### ISSUE TITLE
Task: Create Demo activity

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#100]
Test opening multilple demo activities. 
#9

**Comment by N1ks0n08** [comment]
Commit: 2982ba378235716f0e7599fa1f91f00259b0df13
This issue will have to continue on towards the future due to complication of moving pre-existing main UI layout into 3 different UI fragments to allow for seamless UI navigation through the use of a navigation bar.

**Comment by N1ks0n08** [comment]
Commit: d053e2375d774068675a6ef98e222c243adba2d8
While a new demo activity was not created, fragment views have been implemented to allow for multiple views to be accessed by the user without the need to create an entirely new activity.
