### ISSUE TITLE
Task: Fix MathQuill text box to match stylistic design.

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#105]
Fix MathQuill text box to match stylistic design, and add labels for AST.
#11

**Comment by Hambreyola** [comment]
c96314b80e95f494983022bd06c21e05d66b44db
Fully implemented a proper solution for Mathquill and labeled AST (so that users can tell what the image is before they enter an equation), along with some minor website Improvements.
