### ISSUE TITLE
Task: Finish About Section, update UI

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#109]
Finalize about section by adding project descriptions, update UI to be consistent with website.
#9

**Comment by N1ks0n08** [comment]
Commit: cdadb6ff42678716615a55cb653d31a040509bf1
Addition of UI updates, addition of About section, optimization/improved clarity of code to reduce confusion from boilerplate code.
