### ISSUE TITLE
John's Story: Evaluate Mobile Frameworks

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#11]
As John Doe, a calculus student, I want a nice looking user interface that meshes well with the rest of my websites and mobile apps so that it is easily navigable and convient for me. 
Evaluate UI/UX design technologies (i.e. libraries, backends, and front end like bootstrap) for a viable solution

**Comment by DragonflyRobotics** [comment]
Since finalizing the Canva design is taking longer than expected, we need to delay the decision of the web framework so we can get one that suits all of our needs.

**Comment by ShivanshiDas** [comment]
Relates to #34 and #21
