### ISSUE TITLE
Task: Setup an Android Studio project for Development with the latest Gradle

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#17]
Install the latest Android studio and get the compilation to work with the computer and run the Android simulator. #9

**Comment by N1ks0n08** [comment]
The AndroidApp project is currently running smoothly on the Android simulator with the latest Gradle and AndroidStudio version.
Commit: d8024eaf0abed1b40e33a385c23e86cabdeefc3d

**Comment by N1ks0n08** [comment]
The AndroidApp project is currently running smoothly on the Android simulator with the latest Gradle and AndroidStudio version.
Commit: d8024eaf0abed1b40e33a385c23e86cabdeefc3d
