### ISSUE TITLE
Task: Evaluate Web Frameworks

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#21]
Evaluate different web frameworks that can easily satisfy the initial UI/UX design plans. #6
Some to try:
* Tailwind
* Bootstrap/Bootstrap Studio for drag-n-drop
* React 
* Flutter

**Comment by Hambreyola** [comment]
Researched into all the frameworks listed above, and more. Decided to use Tailwind or Bootstrap based on how easy they are to learn (tutorials and other resources), how powerful they are (how many features), and how effective they would be for our project specifically.

**Comment by DragonflyRobotics** [comment]
The final verdict was to predominantly use Tailwind because it is simpler to make better-looking UIs and is more modern in some aspects than its alternative, Bootstrap.
