### ISSUE TITLE
Task: Negative functions

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#28]
Create a function/functions that convert equations in the form "-function()" to readible tokens for the algorithm. #27

**Comment by aryanjverma** [comment]
Issue resolved with 1a030b6, where I added a while loop to convert characters in the form "-function()" to a statement in terms of -1, the function, and the operations attached to the function. Modified a function to test whether a string is a function, and added another function to test if a function is in the form "-function()". Additionally, modified the shunting yard algorithm to accept functions..

**Comment by KarthikPeravali** [comment]
Tested for negative numbers (passed) 26e352a16c81260742bb8a74bd8df2ced725adf5
