### ISSUE TITLE
Task: Finalize UI Planning

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#30]
Finish up all UI planning and check with others for evaluation. #6

**Comment by Hambreyola** [comment]
Finished all [UI planning](https://www.canva.com/design/DAF2UG1l4_k/-gwMYhX6NXGBsSGDMRGXbw/edit?utm_content=DAF2UG1l4_k&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton ). Included designs of many different themes, colors, and layouts. Also included the final plan for the website, and planning for the most important part of the website- the calculator.
