### ISSUE TITLE
Task: Modify Android Mobile App

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#31]
Continue creating the app; add buttons, keep it user-friendly, and make sure it's similar to Shivanshi's iOS app. #11

**Comment by N1ks0n08** [comment]
Commit: 0eb62e9dc0560c4e4da7ead11db60d68459dfa11
I have added a button with an actionListener function that allows for a toast message to be popped up when clicked; I have made the layout simple; I have collaborated with the groupto make the Android App to be similar to Shivanshi's iOS app.

**Comment by DragonflyRobotics** [comment]
App tested and works
