### ISSUE TITLE
Task: Modify iOS App

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#32]
Continue creating the app; add buttons, keep it user-friendly, and make sure it's similar to the Android app (communicate with Nikson). #11

**Comment by ShivanshiDas** [comment]
This was implemented in the commit b256ef4. The app has a template for buttons and is ready to be further modified. I need to collaborate with Nikson to make sure that the iOS app is similar to the Android app - that should be moved over to the following week.

**Comment by DragonflyRobotics** [comment]
Task doesn't need QA
