### ISSUE TITLE
Task: Test Cases for Polynomial, Rational, Exponential Functions

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#33]
Create and test test cases for the derivatives of these functions using Poetry tests. #10

**Comment by KarthikPeravali** [comment]
This task was resolved under the commit 26e352a16c81260742bb8a74bd8df2ced725adf5. I tested exponential, polynomial, and rational functions and saw all test cases pass. Issues were found under the negative exponentials but that was resolved by the team.
