### ISSUE TITLE
Task: Add global constants like e and pi for user convenience

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#37]
This task requires the explicit entry of the Pi UTF-8 and e characters to be recognized and replaced with their decimal (high precision) expansions for computing. This ties into #27 since trigonometric functions often utilize Pi, and logarithms often use e.

**Comment by aryanjverma** [comment]
60f0226c41fccb74f07ede5e2c3eeb6a08ddee0c

**Comment by DragonflyRobotics** [comment]
With commit c6bc1011d02014cb24e37f2000ca9cb40ec53091, several tests include Pi and e and they all pass. No specific code coverage but preprocess is well covered.
