### ISSUE TITLE
Task: Write Java code that interfaces with POST endpoint

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#42]
Write a basic script detached from the Android app that uses JSON POST requests to interface with the Vapor endpoint. #38

**Comment by DragonflyRobotics** [comment]
This task is backlogged because to run a POST request in Android studio, we need to multithread/async the process, which involves excessive complication. Instead, we will write a stand-alone Java program compile it with JDK, and run it with JRE to ensure that we can at least make the REST call.

**Comment by N1ks0n08** [comment]
a64019488df8e4f8f35df32182146a45014f46aa

Independent java class working that correctly sends POST request and sends/retrieves JSON data.
