### ISSUE TITLE
Task: Write Swift Script to interface with POST endpoint

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#43]
Write a basic script detached from the iOS app that uses JSON POST requests to interface with the Vapor endpoint. #38

**Comment by aryanjverma** [comment]
Note: Due to NASA Hunch, Shivanshi is unable to complete the task at the moment.

**Comment by ShivanshiDas** [comment]
Resolved with: [24a67c3](https://github.com/Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024/commit/24a67c3a0a88807701e5969942a638c80c2f6888)
