### ISSUE TITLE
Task: Add Buttons and User Interaction

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#45]
Create buttons, text input, and output for the Android app. #9

**Comment by N1ks0n08** [comment]
9f7d15236feec982a99e6effbf20038f299cfceb

User input interaction added; Buttons allow user input to be sent for processing.

**Comment by DragonflyRobotics** [comment]
There is nothing to test here and if the buttons were tested once, they should work so this task is done!
