### ISSUE TITLE
Task: Add Inverse Reciprocal Trig Functions

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#47]
Add function identities such as arcsec, arccsc, arccot. #27

**Comment by DragonflyRobotics** [comment]
This feature enhancement was resolved with the commit 4f0c9727bf1eefcaba7f3ac0ae5c3b25b8e56e1b

**Comment by DragonflyRobotics** [comment]
Finished testing this on c6bc1011d02014cb24e37f2000ca9cb40ec53091 and have >88% code coverage. Tests might fail because restricted mathematical domain.
