### ISSUE TITLE
Task: Test Coeffecients

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#48]
Create complex test cases for the tokenizer to test coeffecients (examples: 2x,-5cos(x), e(ln(x))). #10 
Edit for sprint-10: There was an error so the tokenizer had to be fixed; test it agian with double constants like 2e or -4pi.

**Comment by aryanjverma** [comment]
Issue resolved with 1ab7645

**Comment by KarthikPeravali** [comment]
Tested for coefficients  (passed) 8bc7c2b0a6cd47476b1f2fa3c08d39a782c71973
