### ISSUE TITLE
Task: Use Canva to plan some basic UI.

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#5]
Use Canva to make some basic UI/UX plans. #6

**Comment by Hambreyola** [comment]
<img width="428" alt="Screenshot 2024-01-12 at 10 20 35 AM" src="https://github.com/Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024/assets/97413192/efc723b9-e51a-4a87-abac-52c25ef03c0f">

Used Canva to create some basic UI/UX designs and aspects to help plan for the website.

**Comment by Hambreyola** [comment]
<img width="428" alt="Screenshot 2024-01-12 at 10 20 35 AM" src="https://github.com/Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024/assets/97413192/efc723b9-e51a-4a87-abac-52c25ef03c0f">

Used Canva to create some basic UI/UX designs and aspects to help plan for the website.
