### ISSUE TITLE
Task: Fix Coeffecient Tokenizer

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#50]
Fix the error regarding two constants multiplied by each other.

#27

**Comment by aryanjverma** [comment]
Pushed to QA with ecf4daa328ee5147ead33d2b0f6fb26199eda518

**Comment by KarthikPeravali** [comment]
Incorporated test cases with Coefficient Tokenizer (passed) 7cf9b6896de3ad7c2bf060496a170d748c9a3348
