### ISSUE TITLE
Task: Start Working on Functions with multiple x's

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#52]
Modify numerical engine to evaluate and differentiate functions with multiple x's (x+x), (x(x+1)).
#27

**Comment by DragonflyRobotics** [comment]
Resolved with: f1ddbcb6d1a66b1a1118cca563142e1223e32021

**Comment by KarthikPeravali** [comment]
Tested with: 7cf9b6896de3ad7c2bf060496a170d748c9a3348
