### ISSUE TITLE
Task: Code Website Without Tailwand

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#53]
Start implementing Tailwand into the website.
#11

**Comment by DragonflyRobotics** [comment]
Changed this from MVP to Alpha since a nice graphical UI is not strictly necessary for MVP.

**Comment by aryanjverma** [comment]
Code the website using your own HTML and implement the logos that have been approved by the team.
#11

**Comment by Hambreyola** [comment]
a3da92cce0c7bd9b9ea8bb1c475a4b35c6396344

Added bare-bones HTML website with heading, proper layout organization, and working post request in javascript
