### ISSUE TITLE
Task: Fix tetrations neigboring x values.

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#55]
Currently, doing x*x or x^x doesn't work since a second x node is not being made. #27

**Comment by DragonflyRobotics** [comment]
This issue was resolved with the commit f1ddbcb6d1a66b1a1118cca563142e1223e32021

**Comment by KarthikPeravali** [comment]
Tested with: ed279846a9959e6401efcc619eb3901b9ccae2d1, cafb5748f202edcfd24c24a6f6d75cc89504f9ab
