### ISSUE TITLE
Task: Make Icon and work on UI

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#58]
Make Icon and Logo for webstie to display our brand, and work on UI.
#11

**Comment by Hambreyola** [comment]
Planned for a variety of different logos/icons and finalized a decision with the team. We will be using the first design shown in the image below.

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024/assets/97413192/964a4b6e-66fc-4c36-be7c-34ccf1626aed)
