### ISSUE TITLE
Jimmy's Story: Plan UI

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#6]
As Jimmy, a guy who is  learning about the math behind AI, I want to have an interactable user interface that can help him use and undertand automatic differentiation and how it relates to AI.

**Comment by Hambreyola** [comment]
5fd725a498816d6815268e86b32ebc0fc55fe615 

Used canva to plan for UI/UX design. Planned for different aspects of our project by employing various themes, colors and layouts.

**Comment by Hambreyola** [comment]
The image below details more on the planning that was mentioned in my previous message.

![Image](https://github.com/Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024/assets/97413192/d7874882-0528-4546-bbc3-0b1d49ce66b2)
