### ISSUE TITLE
Task: Create invariant enforcements for prohibited equation notation

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#63]
Create statements that return erorrs when prohibited equations such as (x+1)(x+2) or (x+5)sin(x) are inputted, along with reasons behind the errors.
#62

**Comment by aryanjverma** [comment]
Task pushed to QA with 0e307c7

**Comment by KarthikPeravali** [comment]
Tested with: 7cf9b6896de3ad7c2bf060496a170d748c9a3348
