### ISSUE TITLE
Task: Keep UI Consistent throughout Apps and Website

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#64]
Work on UI together so that the Android App, iOS App, and website are all consistent. Ensure that the UI is visually appealling. 
#6

**Comment by N1ks0n08** [comment]
ab1c02998e6143ba125a4d3eed8f8bdb9353f765

I have changed the color scheme in accordance with the UI/UX Designer; I will have to implement logo and app icon later.
