### ISSUE TITLE
Task: Parse JSON Output into Readable Info

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#69]
Create a parser that turns JSON Output into information that can be easily read and understood by users.
#38

**Comment by DragonflyRobotics** [comment]
This is not strictly necessary for MVP since this is primarily for testers and isn't crucial for the system to function so I will move this to Alpha.

**Comment by N1ks0n08** [comment]
2fb7c9f324bda23037e9d8204cf6698e21811d8c

Changes to the server JSON response have been made to be human readable.
