### ISSUE TITLE
Wilson's Story: Auto Diff Algorithim

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#7]
As Wilson, a calculus student, I want to be able to find the derivatives of basic functions using the Automatic Differentiation algorithim, so that I can use them to do my Calculus Homework.
Work on auto diff algorithm, get it working for basic functions.

**Comment by DragonflyRobotics** [comment]
The basic differentiation algorithm is implemented with commit: c1769c522e18370f439d659f5fa180ef783d4d8b. It can currently do chain rule, product, quotient, and sum/difference equations in any combination. It can also handle exponentials.

**Comment by DragonflyRobotics** [comment]
After checking the coverage, it seems as though there is a significant amount of uncovered checks that are needed so although the feature is complete, the item must be backlogged for more QA.

**Comment by KarthikPeravali** [comment]
Chain Differentiation works with the exception of the distribution and factoring. of negative numbers. Requesting to create a seperate issue on negatives, and complete this task
