### ISSUE TITLE
Task: Fix Tokenizer for powers

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#70]
Modify the tokenizer so it correctly interprets statements like "e^x+2".
#27

**Comment by aryanjverma** [comment]
Pushed to QA with 4505d02 (this will  not be implemented into MVP as it needs to be tested first, it will go in alpha instead).

**Comment by KarthikPeravali** [comment]
tested wiht: 26e352a16c81260742bb8a74bd8df2ced725adf5
