### ISSUE TITLE
Task: Test the Apps and Website

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#71]
Ensure that the iOS app, Android app, and website to ensure that they are up to quality standards for the MVP.
#10

**Comment by DragonflyRobotics** [comment]
Resolved with the start of #74 as the entire team helped test the Website and android app. The iOS app will be added to MVP shortly after as a patch fix since NASA hunch has delayed its progress significantly
