### ISSUE TITLE
Task: Utilize LiveData

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#79]
Make a LiveData display to display data and continuously update the UI. #6

**Comment by N1ks0n08** [comment]
Merge: 2ca93f4 4e3ff8b
Commit: 2ca93f42706d797d9029dc7d1a925103ceddbf2c
Addition of MutableLiveData object instead of LiveData to allow for result display mutation depending on different equation/input.
