### ISSUE TITLE
Raj's Story: Andriod App

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#9]
Raj, an aspiring math student, wants an app on his Android phone so that he can use the Automatic Differentiation algorithm to help him on his math assignments from the convince of his phone. 
Setup Android Studio and start working on app.

**Comment by N1ks0n08** [comment]
The Android Studio code for the Android App is currently under production.
Commit: d8024eaf0abed1b40e33a385c23e86cabdeefc3d

**Comment by KarthikPeravali** [comment]
The Android App passed coding practices coverage for tested test cases with minimal changes da885fb623e0b4234fbe913898d8cab414819edb
