### ISSUE TITLE
Task: Add more details to website descriptions 

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#91]
On the website, add more details and information about the calculator (how to use it), valid functions so that users can know what they can and cant do. 
#6

**Comment by Hambreyola** [comment]
82a5f7c6a026740b6bfa05ab56561f343b85ccfd

I added details to the website's About section, including a list of allowed functions and how to use the calculator. I also added a section for applications of Automatic Differentiation and a section for why it is used specifically over manually- computed differentiation.
