### ISSUE TITLE
Task: Make UI on Android Professional 

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#92]
Make UI on Android more professional by removing unnecessary buttons and making output text more professional. 
#9

**Comment by N1ks0n08** [comment]
Commit: a04552b234184eb32d68ae9a9dba90ba3d070bdb
Addition of changes: commenting out unnecessary UI testing code to make the Android application appear more professional for users.
