### ISSUE TITLE
Error: Coefficients don't work at all.

### ISSUE THREAD

**Issue by DragonflyRobotics** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#94]
A majority of our tests are critically failing because the coefficient system is failing. Currently, ex, 2x, or -x don't work. This also applies to trigonometric functions. Either it completely neglects the coefficient or it gets stuck in an infinite loop. In addition to fixing this error, let us try to also add a way to check for infinite loops and crash the code before the server dies.

**Comment by aryanjverma** [comment]
Have u tried checking my branch? I know its called DNE Invariant enforcements but I found some errors with coeffecients so I decided to use that branch to fix them as well, and I'm checking now and its working for everything that I have tried.

**Comment by aryanjverma** [comment]
Bug fixed with #94, also next week a merge will be needed between dev and my branch.
