### ISSUE TITLE
Task: Successfully Implement a Navigation Bar

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#99]
Successfully Implement a Navigation Bar to improve user experience. 
#9

**Comment by aryanjverma** [comment]
Task moved to sprint 19, it will take longer than expected.

**Comment by N1ks0n08** [comment]
Commit: d053e2375d774068675a6ef98e222c243adba2d8
Successful addition of bottom navigation bar to allow the user to easily switch between the main utility page and the about section fragments.
